//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentGroup
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grades
    {
        public int GradeID { get; set; }
        public int StudentID { get; set; }
        public int GroupSubjectTeacherID { get; set; }
        public int GradeValue { get; set; }
        public Nullable<System.DateTime> GradeDate { get; set; }
    
        public virtual GroupSubjectTeacher GroupSubjectTeacher { get; set; }
        public virtual Students Students { get; set; }
    }
}
